@echo off
setlocal

set MYSQL_USER=root
set MYSQL_PASS=wxl127.yl
set DB_NAME=travel_planner

:: 创建数据库
mysql -u %MYSQL_USER% -p%MYSQL_PASS% -e "CREATE DATABASE IF NOT EXISTS %DB_NAME%;"

:: 使用数据库并创建表
mysql -u %MYSQL_USER% -p%MYSQL_PASS% -e "USE %DB_NAME%; CREATE TABLE IF NOT EXISTS users (id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL); CREATE TABLE IF NOT EXISTS trips (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255) NOT NULL, destination VARCHAR(255) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, user_id BIGINT, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE); CREATE TABLE IF NOT EXISTS itineraries (id BIGINT PRIMARY KEY AUTO_INCREMENT, activity VARCHAR(255) NOT NULL, date DATE NOT NULL, time VARCHAR(50) NOT NULL, location VARCHAR(255) NOT NULL, description TEXT, trip_id BIGINT, FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE); CREATE TABLE IF NOT EXISTS bookings (id BIGINT PRIMARY KEY AUTO_INCREMENT, type VARCHAR(50) NOT NULL, booking_number VARCHAR(255) NOT NULL, booking_date DATE NOT NULL, status VARCHAR(50) NOT NULL, price DOUBLE NOT NULL, trip_id BIGINT, FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE);"

echo 数据库初始化完成！
pause